### PR TITLE
Fix issue that caused database rename to and from `saved` to fail

### PR DESCRIPTION
**Pull request by ahoppen**
`llvm::sys::fs::rename` cannot rename directories becasue it creates a file handle for the file to rename, which doesn't work for directories. Implement a custom rename function that uses `MoveFileW` on Windows. 

Fixes https://github.com/swiftlang/sourcekit-lsp/issues/1750

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/swiftlang/swift/pull/77015

@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]
Pretty weird but... 🤷

**Comment by ahoppen** [comment]
For the record, `llvm::sys::fs::rename` tries to create a file handle for the directory using `CreateFileW` and that fails. From [Windows documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) of `CreateFileW`:

> Creates or opens a file or I/O device. The most commonly used I/O devices are as follows: file, file stream, directory,

> To open a directory using CreateFile, specify the FILE_FLAG_BACKUP_SEMANTICS flag as part of dwFlagsAndAttributes

> FILE_FLAG_BACKUP_SEMANTICS: The file is being opened or created for a backup or restore operation. The system ensures that the calling process overrides file security checks when the process has SE_BACKUP_NAME and SE_RESTORE_NAME privileges. For more information, see [Changing Privileges in a Token](https://learn.microsoft.com/en-us/windows/desktop/SecBP/changing-privileges-in-a-token).

So, looks like `CreateFileW` can open directories but it’s not really supposed to except for backup purposes and should not be the go-to solution for renaming directories.

**Pull request merged**
